/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.io.File;
import java.util.Scanner;
package lab6;

public class Components {
   
    public static void main(String[] args) {
        File inputFile = new File(args);
        Scanner sc = new Scanner(inputFile);
        int nodeNum=sc.nextInt();
        while(sc.hasNextLine()){
            sc.nextLine().charAt(0)=
        }
    }
}
